In [16]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))
def softmax(x):
    c=np.max(x)
    exp_x=np.exp(x-c)
    return exp_x/sum(exp_x)
def identity_function(x):
    return x
def init_network():
    network={}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([[0.1, 0.2, 0.3]])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([[0.1, 0.2]])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([[0.1, 0.2]])
    return network
def forward(network, x):
    # layer1
    W1=network['W1']
    b1=network['b1']
    a1=np.dot(x,W1)+b1
    z1=sigmoid(a1)
    # layer2
    W2=network['W2']
    b2=network['b2']
    a2=np.dot(z1,W2)+b2
    z2=sigmoid(a2)
    # layer3
    W3=network['W3']
    b3=network['b3']
    a3=np.dot(z2,W3)+b3
    y=identity_function(a3)
    return y

network = init_network()
x=np.array([1.0,0.5])
y=forward(network,x)
print(y) #[0.31682708 0.69627909]

[[0.31682708 0.69627909]]


In [19]:
import numpy as np
import random

def identity_function(x):
    return x
def init_network():
    network={}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([[0.1, 0.2, 0.3]])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([[0.1, 0.2]])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([[0.1, 0.2]])
    return network
def forward(network, x):
    # layer1
    W1=network['W1']
    b1=network['b1']
    a1=np.dot(x,W1)+b1
    z1=sigmoid(a1)
    # layer2
    W2=network['W2']
    b2=network['b2']
    a2=np.dot(z1,W2)+b2
    z2=sigmoid(a2)
    # layer3
    W3=network['W3']
    b3=network['b3']
    a3=np.dot(z2,W3)+b3
    y=identity_function(a3)
    return y

network = init_network()
batch_size = 16
x=np.random.rand(1000,2)
for i in range(0,len(x),batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = forward(network,x_batch)
    print(f"{y_batch}\n")

[[0.31740743 0.69756783]
 [0.31570989 0.69377838]
 [0.31373104 0.68939838]
 [0.31171117 0.684908  ]
 [0.31727969 0.6972749 ]
 [0.31592441 0.69425623]
 [0.31182938 0.68517538]
 [0.31008985 0.68131215]
 [0.31874405 0.70053499]
 [0.31417917 0.69038646]
 [0.31429979 0.69065753]
 [0.30993421 0.68096967]
 [0.31454853 0.69121424]
 [0.31728129 0.69727683]
 [0.31532898 0.69294915]
 [0.31251675 0.68670443]]

[[0.31327996 0.68839926]
 [0.31419299 0.69043059]
 [0.31445124 0.69099253]
 [0.31531395 0.69290045]
 [0.31470881 0.69156878]
 [0.3187859  0.70062855]
 [0.31549266 0.69330237]
 [0.31596359 0.69435876]
 [0.31546675 0.6932416 ]
 [0.3102893  0.68175475]
 [0.31412345 0.69026386]
 [0.31488177 0.69195914]
 [0.31743745 0.69763516]
 [0.31482106 0.69180099]
 [0.31250058 0.68667223]
 [0.31486413 0.69190634]]

[[0.31126604 0.68391997]
 [0.3145562  0.69122513]
 [0.31354041 0.68896738]
 [0.31622817 0.69493992]
 [0.30973472 0.68053181]
 [0.31134442 0.68409938]
 [0.31504132 0.69230168]
 [0.30967749 0.680400

## 感想
ニューラルネットワークの基礎が理解できたとともに、Numpyの便利さも理解できたと思う。
## 参考文献
ゼロから作るDeep Learning 著：斎藤康毅